### ISSUE TITLE
Common inside module

### ISSUE THREAD

**Issue by sushanyadav** [Aztriltus/nextjs-ts-tailwind-template#14]
What happens if a section is shared by only two modules?
Consider a header section that is only present on the home and about pages.

 I don't think @/common is suitable spot in this context cause It is not generic to all the pages but it is only shareable for 2 modules.
 
Thoughts?
@ayungavis @andrehadianto @Aztriltus

**Comment by Aztriltus** [comment]
One way I've overcome this is by making a new parent module to the 2 modules that reuse logic. So we'll have to move the 2 modules into that folder. 

So in this parent folder, you can include more components e.g. `/parentA/components` (or even hooks, common functions, etc) while the 2 child modules will be `/parentA/moduleA` and `/parentA/moduleB`. 

If this is not suitable, then I think there's no choice but to put it under `/common` though 🤔 I think it's fine if only 2 modules use a common component. 
- We can make it like a guideline that as long as 2 or more modules use a component, then put into common. 
- It might be likely that in the future, this common component may be used by another module again, so I think it's still ok. 
- Since this might be rare, having a few common components this way won't cause too much distraction in the common components folder too I feel

**Comment by sushanyadav** [comment]
Yea totally make sense. Thanks @Aztriltus
